import { useState, useRef } from "react";
import { Upload, Search, FileText, Image, File, Download, Share2, Trash2, X, Plus, Copy, Mail, Link, AlertTriangle, Check } from "lucide-react";
import { toast } from "sonner";
import { useDocument } from "@/hooks/useDocument";
import type { DocumentRecord } from "@/hooks/useDocument";

const typeIcons: Record<string, typeof FileText> = { PDF: FileText, Excel: File, Image: Image, Word: FileText, Other: File };
const typeColors: Record<string, string> = {
  PDF: "bg-destructive/15 text-destructive",
  Excel: "bg-success/15 text-success",
  Image: "bg-accent/15 text-accent",
  Word: "bg-primary/15 text-primary",
  Other: "bg-secondary text-muted-foreground",
};

const accessColors: Record<string, string> = {
  All: "bg-success/15 text-success",
  Engineering: "bg-primary/15 text-primary",
  Design: "bg-accent/15 text-accent",
  Finance: "bg-warning/15 text-warning",
  Marketing: "bg-destructive/15 text-destructive",
  HR: "bg-success/15 text-success",
  Operations: "bg-secondary text-muted-foreground",
};

function getFileType(fileName: string): DocumentRecord["type"] {
  const ext = fileName.split(".").pop()?.toLowerCase() || "";
  if (ext === "pdf") return "PDF";
  if (["xlsx", "xls", "csv"].includes(ext)) return "Excel";
  if (["png", "jpg", "jpeg", "gif", "svg", "webp"].includes(ext)) return "Image";
  if (["doc", "docx"].includes(ext)) return "Word";
  return "Other";
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return bytes + " B";
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(0) + " KB";
  return (bytes / (1024 * 1024)).toFixed(1) + " MB";
}

export default function Documents() {
  const { documents, addDocument, removeDocument } = useDocument();
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("All Types");
  const [deptFilter, setDeptFilter] = useState("All Departments");
  const [dragOver, setDragOver] = useState(false);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Upload modal form state
  const [uploadName, setUploadName] = useState("");
  const [uploadType, setUploadType] = useState<DocumentRecord["type"]>("PDF");
  const [uploadSize, setUploadSize] = useState("0 KB");
  const [uploadAccess, setUploadAccess] = useState("All");
  const [uploadVersion, setUploadVersion] = useState("v1.0");

  const filtered = documents.filter(d => {
    const matchSearch = d.name.toLowerCase().includes(search.toLowerCase());
    const matchType = typeFilter === "All Types" || d.type === typeFilter;
    const matchDept = deptFilter === "All Departments" || d.access === deptFilter;
    return matchSearch && matchType && matchDept;
  });

  const handleFileSelect = (files: FileList | null) => {
    if (!files || files.length === 0) return;

    const file = files[0];
    const detectedType = getFileType(file.name);
    const size = formatFileSize(file.size);

    setUploadName(file.name);
    setUploadType(detectedType);
    setUploadSize(size);
    setShowUploadModal(true);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    handleFileSelect(e.dataTransfer.files);
  };

  const handleUploadSubmit = () => {
    if (!uploadName) {
      toast.error("Please provide a file name");
      return;
    }

    addDocument({
      name: uploadName,
      type: uploadType,
      size: uploadSize,
      version: uploadVersion,
      access: uploadAccess,
    });

    toast.success(`"${uploadName}" uploaded successfully`);
    setShowUploadModal(false);
    setUploadName("");
    setUploadType("PDF");
    setUploadSize("0 KB");
    setUploadAccess("All");
    setUploadVersion("v1.0");
  };

  const handleDelete = (id: number, name: string) => {
    removeDocument(id);
    toast.success(`"${name}" deleted`);
    setDeleteDoc(null);
  };

  // State for share and delete modals
  const [shareDoc, setShareDoc] = useState<DocumentRecord | null>(null);
  const [deleteDoc, setDeleteDoc] = useState<DocumentRecord | null>(null);
  const [linkCopied, setLinkCopied] = useState(false);

  // Download handler - generates a placeholder file and triggers download
  const handleDownload = (doc: DocumentRecord) => {
    const mimeTypes: Record<string, string> = {
      PDF: "application/pdf",
      Excel: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      Image: "image/png",
      Word: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      Other: "application/octet-stream",
    };

    const content = `--- ${doc.name} ---\nType: ${doc.type}\nSize: ${doc.size}\nUploaded By: ${doc.by}\nDate: ${doc.date}\nVersion: ${doc.version}\nAccess: ${doc.access}\n\n[This is a placeholder file generated by Resonira Workplace Document Management]`;

    const blob = new Blob([content], { type: mimeTypes[doc.type] || "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = doc.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`Downloading "${doc.name}"`);
  };

  // Share handler - copy link to clipboard
  const handleCopyLink = (doc: DocumentRecord) => {
    const shareUrl = `${window.location.origin}/documents?file=${encodeURIComponent(doc.name)}&id=${doc.id}`;
    navigator.clipboard.writeText(shareUrl).then(() => {
      setLinkCopied(true);
      toast.success("Link copied to clipboard");
      setTimeout(() => setLinkCopied(false), 2000);
    }).catch(() => {
      toast.error("Failed to copy link");
    });
  };

  // Share via email
  const handleEmailShare = (doc: DocumentRecord) => {
    const subject = encodeURIComponent(`Shared Document: ${doc.name}`);
    const body = encodeURIComponent(
      `Hi,\n\nI'm sharing the following document with you:\n\nFile: ${doc.name}\nType: ${doc.type}\nVersion: ${doc.version}\nSize: ${doc.size}\n\nAccess it here: ${window.location.origin}/documents?file=${encodeURIComponent(doc.name)}&id=${doc.id}\n\nBest regards`
    );
    window.open(`mailto:?subject=${subject}&body=${body}`, "_blank");
    toast.success("Opening email client...");
  };

  return (
    <div className="space-y-6 animate-fade-up">
      <h1 className="text-2xl font-heading font-bold">Document Management</h1>

      {/* Upload Zone */}
      <div
        onDragOver={e => { e.preventDefault(); setDragOver(true); }}
        onDragLeave={() => setDragOver(false)}
        onDrop={handleDrop}
        onClick={() => fileInputRef.current?.click()}
        className={`card-surface border-2 border-dashed p-8 text-center transition-all cursor-pointer ${dragOver ? "border-primary bg-primary/5" : "border-border hover:border-primary/50"}`}
      >
        <Upload size={32} className={`mx-auto mb-3 ${dragOver ? "text-primary" : "text-muted-foreground"}`} />
        <p className="text-sm font-medium">Drag & drop files here</p>
        <p className="text-xs text-muted-foreground mt-1">or click to browse · PDF, DOC, XLS, PNG up to 25MB</p>
        <input
          ref={fileInputRef}
          type="file"
          accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.png,.jpg,.jpeg,.gif,.svg,.webp"
          className="hidden"
          onChange={e => handleFileSelect(e.target.files)}
        />
      </div>

      {/* Toolbar */}
      <div className="flex flex-wrap gap-3">
        <div className="relative flex-1 min-w-[200px] max-w-sm">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search documents..."
            className="w-full bg-secondary border border-border rounded-xl pl-9 pr-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary"
          />
        </div>
        <select
          value={typeFilter}
          onChange={e => setTypeFilter(e.target.value)}
          className="bg-secondary border border-border rounded-xl px-3 py-2 text-sm"
        >
          <option>All Types</option>
          <option>PDF</option>
          <option>Excel</option>
          <option>Image</option>
          <option>Word</option>
        </select>
        <select
          value={deptFilter}
          onChange={e => setDeptFilter(e.target.value)}
          className="bg-secondary border border-border rounded-xl px-3 py-2 text-sm"
        >
          <option>All Departments</option>
          <option>Engineering</option>
          <option>Design</option>
          <option>Marketing</option>
          <option>Finance</option>
          <option>HR</option>
          <option>Operations</option>
        </select>
        <button
          onClick={() => {
            setUploadName("");
            setUploadType("PDF");
            setUploadSize("");
            setUploadAccess("All");
            setUploadVersion("v1.0");
            setShowUploadModal(true);
          }}
          className="gradient-primary text-primary-foreground px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 hover:scale-105 transition-transform"
        >
          <Plus size={16} /> Upload Manual
        </button>
      </div>

      {/* Table */}
      <div className="card-surface overflow-hidden">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border text-muted-foreground text-left">
              <th className="p-3">File</th><th className="p-3">Type</th><th className="p-3">Size</th>
              <th className="p-3">Uploaded By</th><th className="p-3">Version</th><th className="p-3">Access</th><th className="p-3">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 ? (
              <tr>
                <td colSpan={7} className="p-12 text-center text-muted-foreground italic">
                  No documents found. Upload a file to get started.
                </td>
              </tr>
            ) : (
              filtered.map(d => {
                const Icon = typeIcons[d.type] || FileText;
                return (
                  <tr key={d.id} className="border-b border-border/50 hover:bg-secondary/30 transition-colors">
                    <td className="p-3">
                      <div className="flex items-center gap-3">
                        <Icon size={16} className="text-muted-foreground" />
                        <div>
                          <div className="font-medium">{d.name}</div>
                          <div className="text-[11px] text-muted-foreground">{d.date}</div>
                        </div>
                      </div>
                    </td>
                    <td className="p-3"><span className={`badge-pill ${typeColors[d.type] || typeColors.Other}`}>{d.type}</span></td>
                    <td className="p-3 text-muted-foreground">{d.size}</td>
                    <td className="p-3 text-muted-foreground">{d.by}</td>
                    <td className="p-3"><span className="badge-pill bg-accent/15 text-accent">{d.version}</span></td>
                    <td className="p-3"><span className={`badge-pill ${accessColors[d.access] || accessColors.All}`}>{d.access}</span></td>
                    <td className="p-3">
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleDownload(d)}
                          className="p-1.5 rounded-lg hover:bg-primary/10 transition-colors group"
                          title="Download"
                        >
                          <Download size={14} className="text-primary group-hover:scale-110 transition-transform" />
                        </button>
                        <button
                          onClick={() => setShareDoc(d)}
                          className="p-1.5 rounded-lg hover:bg-accent/10 transition-colors group"
                          title="Share"
                        >
                          <Share2 size={14} className="text-muted-foreground group-hover:text-accent group-hover:scale-110 transition-all" />
                        </button>
                        <button
                          onClick={() => setDeleteDoc(d)}
                          className="p-1.5 rounded-lg hover:bg-destructive/10 transition-colors group"
                          title="Delete"
                        >
                          <Trash2 size={14} className="text-destructive group-hover:scale-110 transition-transform" />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

      {/* Upload Details Modal */}
      {showUploadModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-background/70 backdrop-blur-sm" onClick={() => setShowUploadModal(false)} />
          <div className="relative z-10 card-surface p-6 w-full max-w-lg animate-fade-up">
            <div className="flex justify-between items-center mb-5">
              <h2 className="font-heading font-bold text-lg">Upload Document</h2>
              <button onClick={() => setShowUploadModal(false)}><X size={18} className="text-muted-foreground" /></button>
            </div>
            <div className="space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-bold text-muted-foreground uppercase tracking-widest">File Name</label>
                <input
                  value={uploadName}
                  onChange={e => setUploadName(e.target.value)}
                  placeholder="e.g. Project_Report.pdf"
                  className="w-full bg-secondary border border-border rounded-xl px-4 py-3 text-sm focus:border-primary outline-none transition-all"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-xs font-bold text-muted-foreground uppercase tracking-widest">File Type</label>
                  <select
                    value={uploadType}
                    onChange={e => setUploadType(e.target.value as DocumentRecord["type"])}
                    className="w-full bg-secondary border border-border rounded-xl px-4 py-3 text-sm focus:border-primary outline-none transition-all"
                  >
                    <option>PDF</option>
                    <option>Excel</option>
                    <option>Image</option>
                    <option>Word</option>
                    <option>Other</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-bold text-muted-foreground uppercase tracking-widest">File Size</label>
                  <input
                    value={uploadSize}
                    onChange={e => setUploadSize(e.target.value)}
                    placeholder="e.g. 2.4 MB"
                    className="w-full bg-secondary border border-border rounded-xl px-4 py-3 text-sm focus:border-primary outline-none transition-all"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-xs font-bold text-muted-foreground uppercase tracking-widest">Access / Department</label>
                  <select
                    value={uploadAccess}
                    onChange={e => setUploadAccess(e.target.value)}
                    className="w-full bg-secondary border border-border rounded-xl px-4 py-3 text-sm focus:border-primary outline-none transition-all"
                  >
                    <option>All</option>
                    <option>Engineering</option>
                    <option>Design</option>
                    <option>Marketing</option>
                    <option>Finance</option>
                    <option>HR</option>
                    <option>Operations</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-bold text-muted-foreground uppercase tracking-widest">Version</label>
                  <input
                    value={uploadVersion}
                    onChange={e => setUploadVersion(e.target.value)}
                    placeholder="e.g. v1.0"
                    className="w-full bg-secondary border border-border rounded-xl px-4 py-3 text-sm focus:border-primary outline-none transition-all"
                  />
                </div>
              </div>
            </div>

            <button
              onClick={handleUploadSubmit}
              className="gradient-primary text-primary-foreground w-full mt-6 py-3 rounded-xl text-sm font-bold shadow-xl hover:opacity-90 transition-all flex items-center justify-center gap-2"
            >
              <Upload size={18} /> Upload Document
            </button>
          </div>
        </div>
      )}
      {/* Share Modal */}
      {shareDoc && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-background/70 backdrop-blur-sm" onClick={() => { setShareDoc(null); setLinkCopied(false); }} />
          <div className="relative z-10 card-surface p-6 w-full max-w-md animate-fade-up">
            <div className="flex justify-between items-center mb-5">
              <h2 className="font-heading font-bold text-lg">Share Document</h2>
              <button onClick={() => { setShareDoc(null); setLinkCopied(false); }}>
                <X size={18} className="text-muted-foreground" />
              </button>
            </div>

            {/* File info */}
            <div className="card-surface bg-secondary/30 p-4 rounded-xl mb-5 flex items-center gap-3">
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${typeColors[shareDoc.type] || typeColors.Other}`}>
                <FileText size={20} />
              </div>
              <div className="flex-1 min-w-0">
                <div className="font-medium text-sm truncate">{shareDoc.name}</div>
                <div className="text-xs text-muted-foreground">{shareDoc.size} · {shareDoc.type} · {shareDoc.version}</div>
              </div>
            </div>

            {/* Share link */}
            <div className="space-y-3">
              <label className="text-xs font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                <Link size={12} /> Share Link
              </label>
              <div className="flex gap-2">
                <input
                  readOnly
                  value={`${window.location.origin}/documents?file=${encodeURIComponent(shareDoc.name)}&id=${shareDoc.id}`}
                  className="flex-1 bg-secondary border border-border rounded-xl px-3 py-2.5 text-xs text-muted-foreground focus:outline-none"
                />
                <button
                  onClick={() => handleCopyLink(shareDoc)}
                  className={`px-4 py-2.5 rounded-xl text-sm font-semibold flex items-center gap-2 transition-all ${linkCopied
                    ? "bg-success/15 text-success border border-success/30"
                    : "gradient-primary text-primary-foreground hover:opacity-90"
                    }`}
                >
                  {linkCopied ? <><Check size={14} /> Copied</> : <><Copy size={14} /> Copy</>}
                </button>
              </div>
            </div>

            {/* Share options */}
            <div className="mt-5 space-y-2">
              <label className="text-xs font-bold text-muted-foreground uppercase tracking-widest">Share via</label>
              <div className="grid grid-cols-2 gap-3">
                <button
                  onClick={() => handleEmailShare(shareDoc)}
                  className="flex items-center gap-3 p-3 rounded-xl bg-secondary/50 border border-border hover:border-primary/50 hover:bg-secondary transition-all"
                >
                  <div className="w-8 h-8 rounded-lg bg-primary/15 flex items-center justify-center">
                    <Mail size={16} className="text-primary" />
                  </div>
                  <div className="text-left">
                    <div className="text-sm font-medium">Email</div>
                    <div className="text-[10px] text-muted-foreground">Send via email</div>
                  </div>
                </button>
                <button
                  onClick={() => { handleCopyLink(shareDoc); }}
                  className="flex items-center gap-3 p-3 rounded-xl bg-secondary/50 border border-border hover:border-primary/50 hover:bg-secondary transition-all"
                >
                  <div className="w-8 h-8 rounded-lg bg-accent/15 flex items-center justify-center">
                    <Link size={16} className="text-accent" />
                  </div>
                  <div className="text-left">
                    <div className="text-sm font-medium">Copy Link</div>
                    <div className="text-[10px] text-muted-foreground">Copy to clipboard</div>
                  </div>
                </button>
              </div>
            </div>

            {/* Access info */}
            <div className="mt-5 p-3 rounded-xl bg-warning/5 border border-warning/20 flex items-start gap-2">
              <AlertTriangle size={14} className="text-warning mt-0.5 shrink-0" />
              <p className="text-xs text-muted-foreground">
                This document has <span className="font-bold text-warning">{shareDoc.access}</span> access. Only users with the appropriate permissions can view it.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteDoc && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-background/70 backdrop-blur-sm" onClick={() => setDeleteDoc(null)} />
          <div className="relative z-10 card-surface p-6 w-full max-w-sm animate-fade-up">
            {/* Warning icon */}
            <div className="flex justify-center mb-4">
              <div className="w-14 h-14 rounded-full bg-destructive/15 flex items-center justify-center">
                <Trash2 size={24} className="text-destructive" />
              </div>
            </div>

            <h2 className="font-heading font-bold text-lg text-center mb-2">Delete Document?</h2>
            <p className="text-sm text-muted-foreground text-center mb-2">
              Are you sure you want to delete <span className="font-bold text-foreground">"{deleteDoc.name}"</span>?
            </p>
            <p className="text-xs text-muted-foreground/70 text-center mb-6">
              This action cannot be undone. The document will be permanently removed from both portals.
            </p>

            {/* File info */}
            <div className="bg-secondary/30 p-3 rounded-xl mb-5 flex items-center gap-3">
              <FileText size={16} className="text-muted-foreground shrink-0" />
              <div className="flex-1 min-w-0">
                <div className="text-sm font-medium truncate">{deleteDoc.name}</div>
                <div className="text-[11px] text-muted-foreground">{deleteDoc.size} · Uploaded by {deleteDoc.by}</div>
              </div>
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => setDeleteDoc(null)}
                className="flex-1 py-2.5 rounded-xl border border-border text-sm font-medium hover:bg-secondary transition-all"
              >
                Cancel
              </button>
              <button
                onClick={() => handleDelete(deleteDoc.id, deleteDoc.name)}
                className="flex-1 py-2.5 rounded-xl bg-destructive text-white text-sm font-bold hover:bg-destructive/90 transition-all flex items-center justify-center gap-2"
              >
                <Trash2 size={14} /> Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
